### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by quique**
Several improvements and fixes

### CODE REVIEW

**Comment by daudmalik06** [comment]
hey @quique ,
really thanks for sharing your work and contributing to this package,
i'll test it asap and will merge this happily :)

Thanks
Dawood

**Comment by daudmalik06** [comment]
hey @quique  i've tested your pull request but unfortunately the tests are failing can you give it a try ?
`./vendor/bin/phpunit tests/ChromeTestSuite.php`

thanks

**Comment by quique** [comment]
Fixed!  (Sorry for that)

**Comment by daudmalik06** [comment]
cool that was quick fix, i'll restest and gonna merge it,
thanks again

**Comment by manu-sparheld** [comment]
@daudmalik06 Any updates ?

**Pull request closed without merging**
