### PR TITLE
Make code PSR-2 compliant

### PR DESCRIPTION
**Pull request by tophcodes**
For issue #11.

Updated the code and tests to be PSR-2 compliant. Might have missed some things, which will likely be picked up if the StyleCI PR is merged. Simplified some of the code and reworded some of the phpdocs.

I also renamed `getOutPutDirectory` to `getOutputDirectory` (since output is one word). This change is API breaking though, so you might want to verify if that's what you want. I'd also recommend the same with `getScreenShot` and rename it to `getScreenshot`, but didn't do that in this PR.

### CODE REVIEW

**Comment by daudmalik06** [comment]
@padarom thanks , 
but it's failing all of tests can you fix them please ,

**Comment by tophcodes** [comment]
Had to rewrite some of the tests to add the binary path. If you provide a default value for the binary in the constructor, but a user expects to be able to set the binary afterwards using `setBinaryPath`, it will throw an exception because it immediately checks the default value for validity.

That's what happened in the tests, because chrome isn't installed in `/usr/bin/google-chrome` on my machine.

**Comment by daudmalik06** [comment]
yeah you are right , can you fix them ?

**Comment by tophcodes** [comment]
That's what I did with the latest commit. Didn't show up in this feed for some reason, but it's in the commit list.

**Comment by daudmalik06** [comment]
@padarom  thanks buddy great work ,

**Pull request merged**
